var_dict = {
    'd0_1':{'nbinsx':20, 'xmin':-0.01, 'xmax':0.01, 'titleX':'#mu dxy'},
    'd0_2':{'nbinsx':20, 'xmin':-0.01, 'xmax':0.01, 'titleX':'#tau dxy'},
    'dZ_1':{'nbinsx':20, 'xmin':-0.05, 'xmax':0.05, 'titleX':'#mu dz'},
    'dZ_2':{'nbinsx':20, 'xmin':-0.05, 'xmax':0.05, 'titleX':'#tau dz'},
    'iso_1':{'nbinsx':10, 'xmin':0, 'xmax':0.1, 'titleX':'#mu isolation'},
    #'iso_2':{'nbinsx':10, 'xmin':0, 'xmax':0.3, 'titleX':'#tau isolation'},
    'pt_1':{'nbinsx':13, 'xmin':20., 'xmax':150., 'titleX':'#mu p_{T} (GeV)'},
    'pt_2':{'nbinsx':13, 'xmin':20., 'xmax':150., 'titleX':'#tau p_{T} (GeV)'},
    'eta_1':{'nbinsx':21, 'xmin':-2.1, 'xmax': 2.1, 'titleX':'#eta_{#mu}'},
    'eta_2':{'nbinsx':21, 'xmin':-2.1, 'xmax': 2.1, 'titleX':'#eta_{#tau}'},
    'met':{'nbinsx':25, 'xmin':0., 'xmax':250., 'titleX':'E_{miss}^{T}(GeV)'},
    'mvamet':{'nbinsx':25, 'xmin':0., 'xmax':250., 'titleX':'mva E_{miss}^{T}(GeV)'},
    'mjj':{'nbinsx':11, 'xmin':23., 'xmax':250., 'titleX':'m_{jj} (GeV)'},
    'jdeta':{'nbinsx':13, 'xmin':0, 'xmax': 5.2, 'titleX':'#eta_{j1,j2}'},
    'jeta1eta2':{'nbinsx':20, 'xmin':-10, 'xmax': 10, 'titleX':'#eta_{j1}*#eta_{j2}'},
    'mvapt_sum_VBF':{'nbinsx':14, 'xmin':0, 'xmax': 150, 'titleX':'VBF p_{T} sum'},
    'mvapt_VBF':{'nbinsx':20, 'xmin':100, 'xmax': 400, 'titleX':'VBF p_{T} tot'},
    'jpt_1':{'nbinsx':24, 'xmin':25., 'xmax':250., 'titleX':'leading jet p_{T} (GeV)'},
    'bpt_1':{'nbinsx':12, 'xmin':25., 'xmax':250., 'titleX':'leading bjet p_{T} (GeV)'},
    'jeta_1':{'nbinsx':23, 'xmin':-4.6, 'xmax':4.6, 'titleX':'#eta of leading jet'},
    'beta_1':{'nbinsx':23, 'xmin':-4.6, 'xmax':4.6, 'titleX':'#eta of leading bjet'},
    'jpt_2':{'nbinsx':25, 'xmin':0., 'xmax':250., 'titleX':'subleading jet p_{T} (GeV)'},
    'jeta_2':{'nbinsx':23, 'xmin':-4.6, 'xmax':4.6, 'titleX':'#eta of subleading jet'},
    'njets':{'nbinsx':10, 'xmin':0., 'xmax':10., 'titleX':'number of jets'},
    'nbtag_Vienna':{'nbinsx':3, 'xmin':0., 'xmax':3., 'titleX':'number of bjets'},
    'npv':{'nbinsx':20, 'xmin':0., 'xmax':20., 'titleX':'npv'},
    'rho':{'nbinsx':20, 'xmin':0., 'xmax':20., 'titleX':'rho'},
    'm_vis':{'nbinsx':15, 'xmin':0., 'xmax':150., 'titleX':'M_{#tau#tau}^{vis} (GeV)', 'titleY':'dN/dM_{#tau#tau}^{vis} (10/GeV)'},
    'mt_1':{'nbinsx':15, 'xmin':0., 'xmax':150., 'titleX':'M_{#mu}^{T} (GeV)', 'titleY':'dN/dM_{#mu}^{T} (10/GeV)'},
    'mvamt_1':{'nbinsx':15, 'xmin':0., 'xmax':150., 'titleX':'M_{#mu}^{T} (GeV)', 'titleY':'dN/dM_{#mu}^{T} (10/GeV)'},
    'mt_2':{'nbinsx':25, 'xmin':0., 'xmax':250., 'titleX':'M_{#tau}^{T} (GeV)', 'titleY':'dN/dM_{#tau}^{T} (10/GeV)'},
    'mvamt_2':{'nbinsx':25, 'xmin':0., 'xmax':250., 'titleX':'M_{#tau}^{T} (GeV)', 'titleY':'dN/dM_{#tau}^{T} (10/GeV)'},
    'met_centrality':{'nbinsx':15, 'xmin':-1.5, 'xmax':1.5, 'titleX':'met centrality'},
    'lep_etacentrality':{'nbinsx':10, 'xmin':0, 'xmax':1., 'titleX':'lep etacentrality'},
    'sphericity':{'nbinsx':20, 'xmin':0, 'xmax':0.4, 'titleX':'sphericity'},
    'dr_leptau':{'nbinsx':18, 'xmin':0.5, 'xmax':4.1, 'titleX':'#DeltaR(l,#tau)'},
    'BDTscore':{'nbinsx':20, 'xmin':-1., 'xmax':1., 'titleX':'BDT score'},
    
}
